project_id = "btkjdqelvvqmtguhhkdv"

[functions.diagnostic-webhook]
verify_jwt = false

[functions.shopify-order-webhook]
verify_jwt = false

[functions.ga4-analytics]
verify_jwt = false

[functions.shopify-checkout-webhook]
verify_jwt = false
